# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import piston.models


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='timestamp',
            field=models.IntegerField(default=piston.models.get_default_timestamp),
        ),
    ]
